export const SOURCES = [
  {
    id: 'tsinghua-ctwx',
    name: '清华大学出土文献研究与保护中心',
    shortName: '清华出土文献',
    url: 'https://www.ctwx.tsinghua.edu.cn/kxyj/zxky.htm',
    type: 'web',
    bucket: 'lecture',
    priority: 'high',
    selector: {
      list: 'ul.tr-list li',
      title: 'div.tr-list-tt a, a',
      link: 'div.tr-list-tt a, a',
      date: 'div.tr-list-date',
    },
  },
  {
    id: 'fudan-gwz',
    name: '复旦大学出土文献与古文字研究中心',
    shortName: '复旦出土文献',
    url: 'https://www.fdgwz.org.cn/',
    type: 'web',
    bucket: 'news',
    priority: 'high',
    selector: {
      list: 'div#new_artice table tbody tr, #new_artice tr',
      title: 'td a, a',
      link: 'td a, a',
      date: 'td[align="right"], td:last-child',
    },
  },
  {
    id: 'wuhan-bsm',
    name: '武汉大学简帛研究中心',
    shortName: '武大简帛',
    url: 'http://www.bsm.org.cn/',
    type: 'web',
    bucket: 'news',
    priority: 'medium',
    selector: {
      list: 'li, tr',
      title: 'a[href*="show_article"], a[href*="hanjian"], a',
      link: 'a[href*="show_article"], a[href*="hanjian"], a',
      date: '.date, td:last-child',
    },
  },
  {
    id: 'anhui-hanzi',
    name: '安徽大学汉字发展与应用研究中心',
    shortName: '安大汉字中心',
    url: 'https://hz.ahu.edu.cn/6036/list.htm',
    type: 'web',
    bucket: 'lecture',
    priority: 'medium',
    selector: {
      list: 'ul.vp_article_list li.list_item, li',
      title: 'span.Article_Title, a',
      link: 'a',
      date: 'div.fields.ex_fields, span.Article_PublishDate',
    },
  },
  {
    id: 'xianqin-blog',
    name: '先秦史研究室',
    shortName: '先秦史研究室',
    url: 'https://www.xianqin.org/blog/',
    type: 'web',
    bucket: 'news',
    priority: 'medium',
    selector: {
      list: 'article, .post, .entry',
      title: 'h2 a, h1 a, .entry-title a, a',
      link: 'h2 a, .entry-title a, a',
      date: '.entry-date, time, .post-date',
    },
  },

  { id: 'cnki-wenwu', name: '《文物》', shortName: '文物', url: 'https://rss.cnki.net/knavi/rss/WENW?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-kaogu', name: '《考古》', shortName: '考古', url: 'https://rss.cnki.net/knavi/rss/KAGU?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-kgxb', name: '《考古学报》', shortName: '考古学报', url: 'https://rss.cnki.net/knavi/rss/KGXB?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-ctwx', name: '《出土文献与古文字研究》', shortName: '出土文献', url: 'https://rss.cnki.net/knavi/rss/CTWX?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-qtqj', name: '《青铜器与金文》', shortName: '青铜器与金文', url: 'https://rss.cnki.net/knavi/rss/QTQJ?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-jgys', name: '《甲骨文与殷商史》', shortName: '甲骨文与殷商史', url: 'https://rss.cnki.net/knavi/rss/JGYS?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-gyjw', name: '《古文字研究》', shortName: '古文字研究', url: 'https://rss.cnki.net/knavi/rss/GYJW?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'high' },
  { id: 'cnki-jianbo', name: '《简帛》', shortName: '简帛', url: 'https://rss.cnki.net/knavi/rss/JBJB?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'medium' },
  { id: 'cnki-yindu', name: '《殷都学刊》', shortName: '殷都学刊', url: 'https://rss.cnki.net/knavi/rss/YDXK?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'medium' },
  { id: 'cnki-zyww', name: '《中原文物》', shortName: '中原文物', url: 'https://rss.cnki.net/knavi/rss/ZYWW?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'medium' },
  { id: 'cnki-kgyw', name: '《考古与文物》', shortName: '考古与文物', url: 'https://rss.cnki.net/knavi/rss/KGYW?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'medium' },
  { id: 'cnki-hxkg', name: '《华夏考古》', shortName: '华夏考古', url: 'https://rss.cnki.net/knavi/rss/HXKG?pcode=CJFD,CCJD', type: 'rss', bucket: 'paper', priority: 'medium' },

  {
    id: 'scholar-jinwen',
    name: 'Google Scholar Alert: 金文 铭文',
    shortName: 'Scholar',
    url: 'https://scholar.google.com/scholar_alerts?view_op=list_alerts&hl=zh-CN&alert_query=%E9%87%91%E6%96%87+%E9%93%AD%E6%96%87&num=10&output=rss',
    type: 'rss',
    bucket: 'paper',
    priority: 'medium',
  },
  {
    id: 'rsshub-fudan-mp',
    name: '复旦出土文献公众号',
    shortName: '复旦公众号',
    url: 'https://rsshub.app/wechat/mp/article/MzI5NTM2NzYxNA==',
    fallbackUrls: ['https://rss.shab.fun/wechat/mp/article/MzI5NTM2NzYxNA=='],
    type: 'rss',
    bucket: 'news',
    priority: 'medium',
  },
];

export const BUCKETS = [
  { id: 'highlight', title: '今日重点' },
  { id: 'paper', title: '新论文 / 期刊' },
  { id: 'book', title: '新书与书讯' },
  { id: 'lecture', title: '讲座 / 会议' },
  { id: 'news', title: '新闻与机构动态' },
  { id: 'lowConfidence', title: '低置信度候选' },
];

export const KEYWORDS = {
  strong: [
    '金文', '铭文', '青铜器铭文', '铜器铭文', '钟鼎文', '彝铭', '器铭',
    '青铜器', '有铭铜器', '商周铜器', '西周铜器', '殷周金文',
  ],
  medium: [
    '古文字', '出土文献', '殷商', '西周', '东周', '春秋', '战国',
    '简帛', '甲骨文', '考释', '释读', '著录', '器物', '礼制',
  ],
  weak: [
    '考古', '文物', '博物馆', '新见', '出土', '墓葬', '遗址', '学术',
    '讲座', '会议', '新书', '出版', '论文', '刊物',
  ],
  negative: [
    '现代', '保护材料', '陶瓷', '瓷器', '玻璃', '佛教造像',
  ],
};
