/**
 * 金文资讯站 - 信源配置
 * type: 'rss' | 'web'
 * category: 用于前端分类标签
 */

export const SOURCES = [
  // ── 核心学术机构（网页抓取）──────────────────────────────
  {
    id: 'xianqin-blog',
    name: '先秦史研究室',
    shortName: '先秦史研究室',
    url: 'https://www.xianqin.org/blog/',
    type: 'web',
    selector: {
      list: 'article, .post',
      title: 'h2 a, h1 a, .entry-title a',
      link: 'h2 a, .entry-title a',
      date: '.entry-date, time, .post-date',
    },
    category: '学术机构',
    priority: 'high',
  },
  {
    id: 'wuhan-bsm',
    name: '武汉大学简帛研究中心',
    shortName: '武大简帛',
    url: 'http://www.bsm.org.cn/',
    type: 'web',
    selector: {
      list: 'div#bsm_article ul.article_ul li',
      title: 'a[href*="hanjian"]',
      link: 'a[href*="hanjian"]',
      date: 'li.date',
    },
    category: '学术机构',
    priority: 'high',
  },

  // ── CNKI 期刊 RSS（换用 navi.cnki.net）───────────────────

  // 核心期刊（高优先级）
  {
    id: 'cnki-wenw',
    name: '《文物》',
    shortName: '文物',
    url: 'https://navi.cnki.net/knavi/rss/WENW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'high',
  },
  {
    id: 'cnki-kagu',
    name: '《考古》',
    shortName: '考古',
    url: 'https://navi.cnki.net/knavi/rss/KAGU?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'high',
  },
  {
    id: 'cnki-kgxb',
    name: '《考古学报》',
    shortName: '考古学报',
    url: 'https://navi.cnki.net/knavi/rss/KGXB?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'high',
  },
  {
    id: 'cnki-ctwx',
    name: '《出土文献与古文字研究》',
    shortName: '出土文献',
    url: 'https://navi.cnki.net/knavi/rss/CTWX?pcode=CJFD,CCJD',
    type: 'rss',
    category: '出土文献',
    priority: 'high',
  },
  {
    id: 'cnki-qtqj',
    name: '《青铜器与金文》',
    shortName: '青铜器与金文',
    url: 'https://navi.cnki.net/knavi/rss/QTQJ?pcode=CJFD,CCJD',
    type: 'rss',
    category: '出土文献',
    priority: 'high',
  },
  {
    id: 'cnki-jgys',
    name: '《甲骨文与殷商史》',
    shortName: '甲骨文与殷商史',
    url: 'https://navi.cnki.net/knavi/rss/JGYS?pcode=CJFD,CCJD',
    type: 'rss',
    category: '出土文献',
    priority: 'high',
  },
  {
    id: 'cnki-gyjw',
    name: '《古文字研究》',
    shortName: '古文字研究',
    url: 'https://navi.cnki.net/knavi/rss/GYJW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '出土文献',
    priority: 'high',
  },
  {
    id: 'cnki-jbjb',
    name: '《简帛》',
    shortName: '简帛',
    url: 'https://navi.cnki.net/knavi/rss/JBJB?pcode=CJFD,CCJD',
    type: 'rss',
    category: '出土文献',
    priority: 'high',
  },
  {
    id: 'cnki-ydxk',
    name: '《殷都学刊》',
    shortName: '殷都学刊',
    url: 'https://navi.cnki.net/knavi/rss/YDXK?pcode=CJFD,CCJD',
    type: 'rss',
    category: '出土文献',
    priority: 'high',
  },

  // 地方考古期刊（中优先级）
  {
    id: 'cnki-jhkg',
    name: '《江汉考古》',
    shortName: '江汉考古',
    url: 'https://navi.cnki.net/knavi/rss/JHKG?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-zyww',
    name: '《中原文物》',
    shortName: '中原文物',
    url: 'https://navi.cnki.net/knavi/rss/ZYWW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-kgyw',
    name: '《考古与文物》',
    shortName: '考古与文物',
    url: 'https://navi.cnki.net/knavi/rss/KGYW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-hxkg',
    name: '《华夏考古》',
    shortName: '华夏考古',
    url: 'https://navi.cnki.net/knavi/rss/HXKG?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-ggbw',
    name: '《故宫博物院院刊》',
    shortName: '故宫院刊',
    url: 'https://navi.cnki.net/knavi/rss/GGBW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-zlbk',
    name: '《中国国家博物馆馆刊》',
    shortName: '国家博物馆刊',
    url: 'https://navi.cnki.net/knavi/rss/ZLBK?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-lfww',
    name: '《南方文物》',
    shortName: '南方文物',
    url: 'https://navi.cnki.net/knavi/rss/LFWW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-scww',
    name: '《四川文物》',
    shortName: '四川文物',
    url: 'https://navi.cnki.net/knavi/rss/SCWW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-webo',
    name: '《文博》',
    shortName: '文博',
    url: 'https://navi.cnki.net/knavi/rss/WEBO?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-bjww',
    name: '《北方文物》',
    shortName: '北方文物',
    url: 'https://navi.cnki.net/knavi/rss/BJWW?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-wwcq',
    name: '《文物春秋》',
    shortName: '文物春秋',
    url: 'https://navi.cnki.net/knavi/rss/WWCQ?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-nmwc',
    name: '《草原文物》',
    shortName: '草原文物',
    url: 'https://navi.cnki.net/knavi/rss/NMWC?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-wwjk',
    name: '《文物季刊》',
    shortName: '文物季刊',
    url: 'https://navi.cnki.net/knavi/rss/WWJK?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
  {
    id: 'cnki-kgxj',
    name: '《考古学集刊》',
    shortName: '考古学集刊',
    url: 'https://navi.cnki.net/knavi/rss/KGXJ?pcode=CJFD,CCJD',
    type: 'rss',
    category: '考古文物',
    priority: 'medium',
  },
];

// 金文相关关键词，用于 AI 过滤判断
export const JINSHU_KEYWORDS = [
  // 核心词
  '金文', '青铜器', '铭文', '钟鼎文', '彝铭', '器铭',
  // 器类
  '鼎', '簋', '尊', '卣', '壶', '盘', '爵', '觚', '觯', '钟', '镈', '铎',
  '戈', '剑', '矛', '斧', '戟',
  // 时代
  '商周', '西周', '东周', '春秋', '战国', '殷商',
  // 相关领域
  '出土文献', '简帛', '甲骨文', '古文字', '先秦史',
  '历谱', '月相', '武王克商', '天文历法',
  // 研究方法
  '断代', '考释', '著录', '集成', '图录',
  // 机构/人名相关
  '金文研究', '铭文考', '铭文释读',
];
